//var servers = ["n00dles", "max-hardware", "phantasy", "comptek", "zb-institute", "avmnite-02h", "foodnstuff", "nectar-net", "neo-net", "silver-helix", "the-hub", "rothman-uni", "lexo-corp", "snap-fitness", "unitalife", "icarus", "catalyst", "rho-construction", "aevum-police", "global-pharm", "deltaone", "defcomm", "univ-energy", "nova-med", "solaris", "taiyang-digital", "zeus-med", "infocomm", "zb-def", "I.I.I.I", "alpha-ent", "aerocorp", "omnia", "netlink", "summit-uni", "crush-fitness", "CSEC", "sigma-cosmetics", "joesguns", "hong-fang-tea", "zer0", "omega-net", "johnson-ortho", "syscore", "millenium-fitness", "galactic-cyber", "harakiri-sushi", "iron-gym", "darkweb"];
//var servers = ["n00dles","sigma-cosmetics"];
//var servers = ["n00dles", "max-hardware", "phantasy", "zb-institute", "avmnite-02h", "foodnstuff", "nectar-net", "neo-net", "silver-helix", "the-hub", "rothman-uni", "lexo-corp", "snap-fitness", "unitalife", "icarus", "catalyst", "rho-construction", "aevum-police", "global-pharm", "deltaone", "defcomm", "univ-energy", "nova-med", "solaris", "taiyang-digital", "zeus-med", "infocomm", "zb-def", "I.I.I.I", "alpha-ent", "aerocorp", "omnia", "netlink", "summit-uni", "crush-fitness", "CSEC", "sigma-cosmetics", "joesguns", "hong-fang-tea", "zer0", "omega-net", "johnson-ortho", "syscore", "millenium-fitness", "galactic-cyber", "harakiri-sushi", "iron-gym"];
//20220719 lastest
var servers = ["4sigma","aerocorp","aevum-police","alpha-ent","applied-energetics","avmnite-02h","b-and-a","blade","catalyst","clarkinc","computek","crush-fitness","CSEC","darkweb","defcomm","deltaone","ecorp","foodnstuff","fulcrumassets","fulcrumtech","galactic-cyber","global-pharm","harakiri-sushi","helios","home","hong-fang-tea","I.I.I.I","icarus","infocomm","iron-gym","joesguns","johnson-ortho","kuai-gong","lexo-corp","max-hardware","megacorp","microdyne","millenium-fitness","n00dles","nectar-net","neo-net","netlink","nova-med","nwo","omega-net","omnia","omnitek","phantasy","powerhouse-fitness","rho-construction","rothman-uni","run4theh111z","sigma-cosmetics","silver-helix","snap-fitness","solaris","stormtech","summit-uni","syscore","taiyang-digital","The-Cave","the-hub","titan-labs","unitalife","univ-energy","vitalife","zb-def","zb-institute","zer0","zeus-med"];

//var counter = 0;
//var message = "";
//var openedPorts = 0;

	myScriptNameToRun = "hack-B1.script";
	myScriptThreadAmount = 2400;
	myScriptHost = "home";

for (var counter = 0; counter < servers.length; counter++) {

	target = servers[counter];

	//message = "#" + (counter + 1) + "/" + servers.length + " [" + target + "]";
	var openedPorts = 0;


	myCounterReadable = counter +1;
	myHackingLevel = getHackingLevel();

	targetHackingLevel = getServerRequiredHackingLevel(target);
	targetPortsRequired = getServerNumPortsRequired(target);
	isTargetRooted = hasRootAccess(target);

	_SSH = false;
	_FTP = false;
	_SMTP = false;
	_HTTP = false;
	_SQL = false;
/*
	if (isTargetRooted) {
		tellerOK(myCounterReadable,servers.length,target);
	}*/
	if (myHackingLevel < targetHackingLevel) {
		//message = message + " INSUFF Hack: " + myHackingLevel + "/" + targetHackingLevel;
		tellerInsufHack(myCounterReadable,servers.length,target,myHackingLevel,targetHackingLevel);
	}
	else {
	//	message = message + " LVL: " + myHackingLevel + "/" + targetHackingLevel;

		if (fileExists("BruteSSH.exe")) {
			brutessh(target);
			_SSH = true;
			openedPorts = openedPorts + 1;
		}
		if (fileExists("FTPCrack.exe")) {
			ftpcrack(target);
			_FTP = true
			openedPorts = openedPorts + 1;
		}
		if (fileExists("relaySMTP.exe")) {
			relaysmtp(target);
			_SMTP = true;
			openedPorts = openedPorts + 1;
		}
		if (fileExists("HTTPWorm.exe")) {
			httpworm(target);
			_HTTP = true;
			openedPorts = openedPorts + 1;
		}
		if (fileExists("SQLInject.exe")) {
			sqlinject(target);
			_SQL = true;
			openedPorts = openedPorts + 1;
		}

		if (targetPortsRequired > openedPorts) {
			//message = message + " PORTS NEEDED:" + openedPorts + "/" + targetPortsRequired;
			tellerOpenPorts(myCounterReadable,servers.length,target,myHackingLevel,targetHackingLevel,_SSH,_FTP,_SMTP,_HTTP,_SQL,openedPorts + "/" + targetPortsRequired);
		}
		else {
			nuke(target);
			isTargetRooted = hasRootAccess(target);
			if (isTargetRooted) {
				//message = message + " [nuked]";

				exec(myScriptNameToRun, myScriptHost, myScriptThreadAmount, target);
				//message = message + " hackB1@home x240";

			} else {
				//message = message + " [NOT NUKED] [not script running]";
			}
			teller(myCounterReadable,servers.length,target,myHackingLevel,targetHackingLevel,_SSH,_FTP,_SMTP,_HTTP,_SQL,isTargetRooted,myScriptNameToRun,myScriptThreadAmount);
		}

		//backdoor requires advanced level in the game....
		//installBackdoor(target);
		//tprintf("[%s] backdoor installed", target);
		//hack(target);
		//tprintf("[%s] first hack done", target);

	}

	//tprintf("%s", message);
	////tellerOpenPorts(counter,70,servers.length,1379,1046,true,true,true,false,true,true);
	///test//teller(counter,70,servers.length,1379,1046,true,true,true,true,true,true,"hackB1@home",240);
}

function teller(counter,listLength,serverName,myLvl,reqLvl,isSSHd,isFTPd,isSMTPd,isHTTPd,isSQLd,isNuked,scriptToRun,scriptThreadCount) {
	// [23:38:31] #49/70 [powerhouse-fitness] LVL: 1378/1036 SSH|FTP|SMTP|HTTP|SQL [nuked] hackB1@home x240
	//          [ #000/000 - xxxxxiiiiioooooiiiii - root - 0000:0000 - SSH - FTP - SMTP - HTTP - SQL - ssssssssss * 0000 ]

		tprintf("[#%3d/%3d - %20s - %s - %4d:%-4d -%s-%s-%s-%s-%s- %15s*%-4d]", counter, listLength, serverName, isNuked?"root":"  $>", myLvl, reqLvl, isSSHd?"SSH":"   ", isFTPd?"FTP":"   ", isSMTPd?"SMTP":"    ", isHTTPd?"HTTP":"    ", isSQLd?"SQL":"   ", scriptToRun, scriptThreadCount);
}

function tellerOK(counter,listLength,serverName) {
	//           [#000/000 - xxxxxiiiiioooooiiiii - root                                                                 ]
		tprintf("[#%3d/%3d - %20s - root%57s]", counter, listLength, serverName,"");
}

function tellerInsufHack(counter,listLength,serverName,myLvl,reqLvl) {
	//           [#000/000 - xxxxxiiiiioooooiiiii - __$> - 0000:0000 insufficient                                                    ]
		tprintf("[#%3d/%3d - %20s -   $> - %4d:%-4d - insufficient%30s]", counter, listLength, serverName,myLvl,reqLvl,"");
}

function tellerOpenPorts(counter,listLength,serverName,myLvl,reqLvl,isSSHd,isFTPd,isSMTPd,isHTTPd,isSQLd,neededPorts) {
	//          [ #000/000 - xxxxxiiiiioooooiiiii - root - 0000:0000 - SSH - FTP - SMTP - HTTP - SQL - open more ports   ]
		///tprintf("[#%3d/%3d - %20s - %s - %4d:%-4d -%s-%s-%s-%s-%s- open more ports     ]", counter, listLength, serverName, "  $>", myLvl, reqLvl, isSSHd?"SSH":"   ", isFTPd?"FTP":"   ", isSMTPd?"SMTP":"    ", isHTTPd?"HTTP":"    ", isSQLd?"SQL":"   ");
		tprintf("[#%3d/%3d - %20s - %s - %4d:%-4d -%s-%s-%s-%s-%s- %3s ports to open   ]", counter, listLength, serverName, "  $>", myLvl, reqLvl, isSSHd?"SSH":"   ", isFTPd?"FTP":"   ", isSMTPd?"SMTP":"    ", isHTTPd?"HTTP":"    ", isSQLd?"SQL":"   ",neededPorts);
}